# FROM denoland/deno:alpine-1.17.2
FROM denoland/deno:1.17.2

EXPOSE 7777

WORKDIR /app

CMD [ "run", "--unstable", "--watch", "--allow-net", "--allow-read", "--allow-env", "--no-check", "run-locally.js" ]
 