version: "3.4"

services:
  app:
    build: app
    image: app
    # platform: linux/arm64 | actual: linux/amd64
    # TODO: FIND A DENO IMAGE THAT ALSO WORKS WITH ARM64 ARCHITECTURE
    restart: "no"
    volumes:
      - ./app/:/app
      # - ./app-cache/:app-cache
    ports:
      - 7777:7777
    depends_on:
      - database
      - flyway
    env_file:
      - project.env

  database:
    container_name: database-server
    image: postgres:14.1
    restart: "no"
    env_file:
        - project.env

  flyway:
    image: flyway/flyway:8.4.0-alpine
    # platform: linux/arm64 | actual: linux/amd64
    # TODO: FIND A FLYWAY IMAGE THAT ALSO WORKS WITH ARM64 ARCHITECTURE
    depends_on:
      - database
    volumes:
      - .:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env


  # OBSOLETE 
  # database:
  #   container_name: database-p2-192a0eb0-fc3e-46f0-8961-89d692464f65
  #   image: postgres:14.1
  #   restart: "no"
  #   env_file:
  #       - project.env

  # flyway:
  #   image: flyway/flyway:8.4.0-alpine
  #   depends_on:
  #     - database
  #   volumes:
  #     - .:/flyway/sql
  #   command: -connectRetries=60 -baselineOnMigrate=true migrate
  #   env_file:
  #     - project.env